### ISSUE TITLE
Cannot get widget to display

### ISSUE THREAD

**Issue by gursel58** [Sibilino/yii2-openlayers#1]
I have a new yii2-advanced template setup
I added yii2-openlayers by composer
I added the code from the readme

```
<div id="test">
```

<?php
  use sibilino\yii2\openlayers\OpenLayers;
  use sibilino\yii2\openlayers\OL;
echo OpenLayers::widget([
    'id' => 'test',
    'mapOptions' => [
        'layers' => [
            new OL('layer.Tile', [ // Generates "new ol.layer.Tile()" JS. See below for an explanation of the OL class.
                'source' => new OL('source.MapQuest', [
                    'layer' => 'sat',
                ]),
            ]),
        ],
        'view' => [ // No OL() is required here because of simplified option support (see below)
  //         'center' => new JsExpression('ol.proj.transform([37.41, 8.82], "EPSG:4326", "EPSG:3857")'),
            'zoom' => 4,
        ],
    ],
]);?>  
 </div>

and nothing is displayed.
I am relatively new to Yii2 however have expierence with OL3.
Can you provide some insight on what I may have done wrong ?
Also if I dont comment out the 'center; I get an error about JsExpression

Thanks

**Comment by Sibilino** [comment]
Hello,

Thanks for trying my widget out.

If you are using a `JsExpression` you need to tell Yii what namespace to import it from. Just add another `use` statement, like this:

``` php
use yii\web\JsExpression;
```

I will add it this to the documentation, since it can be confusing.

In addition, you do not need to write the map div yourself. When echoing the widget call, the div with `id="test"` will automatically be generated.

Regards

**Comment by gursel58** [comment]
Once I made the changes you suggested it worked right away.

Thanks for your help.

Great widget!
 
-----Original message-----
