### ISSUE TITLE
Request : more example

### ISSUE THREAD

**Issue by Nico207** [Sibilino/yii2-openlayers#4]
Hello,

is it possible to have more example for using/configuring this widget ?

To be honest, I'm totally newbie in yii developpement and I meet many problem to understand how to use the widget.

I have a form with 2 textInput fields (latitude / longitude, in read only) and this widget.
My wish is when I clic on the map, a mark stay on this point and the fields are filled with the coordinates of it.

Can you help me ?

**Comment by Sibilino** [comment]
Hello!

This widget just makes it easier to integrate the OpenLayers map library into a Yii 2 application. It only helps in defining the configuration to be used by the library, by simplifying the syntax, but it does not have any mapping functionality.

In order to understand how to use OpenLayers, you can read the library's [documentation](http://openlayers.org/en/v3.10.1/doc/) and [examples](http://openlayers.org/en/v3.10.1/examples/). Your use case appears to be similar to [this example](http://openlayers.org/en/v3.10.1/examples/overlay.html). Check how the map.on('click') function extracts the coordinates from `ol.coordinate`.

Hope this helps, good luck!
