### ISSUE TITLE
cant get stylefunction to work

### ISSUE THREAD

**Issue by gursel58** [Sibilino/yii2-openlayers#5]
I am trying to implement a stylefunction on one of my vector layers.
I have tried several different ways to get it to work without success:

my vector layer:
                new OL('layer.Vector', [
                    'name' => '30 Days',
                    'group' =>'Uncorr',
                    'visible' => false,

option one define style to point to a function described earlier in javascript

```
                'style' => 'function(feature,res){return strikestylefunction(feature,res);}',
```

option two tried using the new experimental ol.style.StyleFunction - it appears V3.10.1 does not have the experimental function included.
                'style'=> new OL('style.StyleFunction', 
                            ['feature' => 'name',  
                            'resolution'=> 'resolution',  
                            'style'=>[
                                    new OL('style.Style',[
                                          'image' => new OL('style.Icon',[
                                          'src' => '/bolt-9.png'
                                            ])  
                                        ]),
                                     ],
                            ]), 

Any ideas how I should code the stylefunction ?

Thanks
Greg

**Comment by Sibilino** [comment]
Hello,

For your first option you're passing your JavaScript function as a string,
which will therefore be encoded as a JavaScript string instead of a
function (i. e. surrounded by quotes).

What you need is to use a yii\web\JsExpression object (standard Yii2 way to
inject literal JavaScript):
"style" => new JsExpression("function(feature,res){return
strikestylefunction(feature,res);}"),

Regards

2015-11-04 5:54 GMT+01:00 gursel58 notifications@github.com:

**Comment by gursel58** [comment]
That works

Thanks again.
Greg
